vich_uploader:
    db_driver: orm
    mappings:
        post_image:
            uri_prefix: /uploads/images/posts
            upload_destination: '%kernel.project_dir%/public/uploads/images/posts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer